version: "2"
run:
  go: "1.24.4"
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - depguard
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - mnd
    - nakedret
    - noctx
    - nolintlint
    - revive
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    depguard:
      rules:
        main:
          files:
            - '!**/*_test.go'
            - '!**/test/**'
          allow:
            - $gostd
            - github.com/modelplex/modelplex
            - github.com/jessevdk/go-flags
            - github.com/gorilla/mux
            - github.com/pelletier/go-toml/v2
        tests:
          files:
            - '**/*_test.go'
            - '**/test/**'
          allow:
            - $gostd
            - github.com/modelplex/modelplex
            - github.com/stretchr/testify
            - github.com/jessevdk/go-flags
            - github.com/gorilla/mux
            - github.com/pelletier/go-toml/v2
    dupl:
      threshold: 100
    funlen:
      lines: 100
      statements: 50
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 15
    govet:
      enable:
        - shadow
    lll:
      line-length: 120
    misspell:
      locale: US
  exclusions:
    generated: lax
    rules:
      - linters:
          - funlen
          - lll
          - mnd
        path: _test\.go
      - linters:
          - funlen
          - lll
          - mnd
        path: test/
      - linters:
          - lll
        source: '^//go:generate '
      - path: (.+)\.go$
        text: Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked
      - path: (.+)\.go$
        text: should check returned error before deferring
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
severity:
  default: error
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/modelplex/modelplex
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
