# golangci-lint configuration for Modelplex
run:
  timeout: 5m
  go: '1.21'

linters-settings:
  govet:
    shadow: true
  revive:
    min-confidence: 0
  depguard:
    rules:
      main:
        files:
          - "!**/*_test.go"
          - "!**/test/**"
        allow:
          - $gostd
          - github.com/modelplex/modelplex
          - github.com/jessevdk/go-flags
          - github.com/gorilla/mux
          - github.com/pelletier/go-toml/v2
      tests:
        files:
          - "**/*_test.go"
          - "**/test/**"
        allow:
          - $gostd
          - github.com/modelplex/modelplex
          - github.com/stretchr/testify
          - github.com/jessevdk/go-flags
          - github.com/gorilla/mux
          - github.com/pelletier/go-toml/v2
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 120
  goimports:
    local-prefixes: github.com/modelplex/modelplex
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
  funlen:
    lines: 100
    statements: 50

linters:
  disable-all: true
  enable:
    - bodyclose
    - unused
    - depguard
    - dogsled
    - dupl
    - errcheck
    - copyloopvar
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - revive
    - mnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - mnd
        - funlen
        - lll
    - path: test/
      linters:
        - mnd
        - funlen
        - lll
    - linters:
        - lll
      source: "^//go:generate "

  exclude-use-default: false
  exclude:
    # errcheck: Almost all programs ignore errors on these functions and in most cases it's ok
    - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked
    - should check returned error before deferring

  max-issues-per-linter: 0
  max-same-issues: 0

severity:
  default-severity: error
  case-sensitive: false