# golangci-lint configuration for Modelplex
version: "2"

run:
  timeout: 5m
  go: '1.24.4'

linters:
  settings:
  govet:
    shadow: true
  revive:
    min-confidence: 0
  depguard:
    rules:
      main:
        files:
          - "!**/*_test.go"
          - "!**/test/**"
        allow:
          - $gostd
          - github.com/modelplex/modelplex
          - github.com/jessevdk/go-flags
          - github.com/gorilla/mux
          - github.com/pelletier/go-toml/v2
      tests:
        files:
          - "**/*_test.go"
          - "**/test/**"
        allow:
          - $gostd
          - github.com/modelplex/modelplex
          - github.com/stretchr/testify
          - github.com/jessevdk/go-flags
          - github.com/gorilla/mux
          - github.com/pelletier/go-toml/v2
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 120
  goimports:
    local-prefixes: github.com/modelplex/modelplex
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
  funlen:
    lines: 100
    statements: 50

  default: none
  enable:
    - bodyclose
    - unused
    - depguard
    - dogsled
    - dupl
    - errcheck
    - copyloopvar
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - revive
    - mnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - unconvert
    - unparam
    - whitespace

  exclusions:
    - paths:
        - "**/*_test.go"
        - "**/test/**"
      linters:
        - mnd
        - funlen
        - lll
    - source: "^//go:generate "
      linters:
        - lll
    - texts:
        - "Error return value of .((os\\\\.)?std(out|err)\\\\..*|.*Close|.*Flush|os\\\\.Remove(All)?|.*printf?|os\\\\.(Un)?Setenv). is not checked"
        - "should check returned error before deferring"

output:
  severity:
    default: error